#ifndef _PROFILE_TAB_C_
#define _PROFILE_TAB_C_

#include <stdio.h>
#include "BleAppSetting.h"
#include "host_client.h"

//Ref LL.h,
#define MAX_NUM_CONN_SLV_HDL                    1
#define MAX_NUM_CONN_MAS_HDL                    4
#define MAX_NUM_CONN_HDL                        MAX_NUM_CONN_MAS_HDL+MAX_NUM_CONN_SLV_HDL

#ifdef _HOST_CLIENT_
void ATT_NULL_Noti_Indi(uint8_t connID, uint8_t length, uint8_t *srcCMD)
{
}


void ATT_HRS_Noti(uint8_t connID, uint8_t length, uint8_t *srcCMD)
{
}


void ATT_UDF01S_UDATN01_Noti(uint8_t connID, uint8_t length, uint8_t *srcCMD)
{
}

const Uint8 ATT_INVALID_TYPE[] =
{
    0, 0,
};


const Uint8 ATT_TYPE_PRIMARY_SERVICE[] =
{
    GATT_DECLARATIONS_PRIMARY_SERVICE, GATT_DECLARATIONS,
};


const Uint8 ATT_TYPE_SECONDARY_SERVICE[] =
{
    GATT_DECLARATIONS_SECONDARY_SERVICE, GATT_DECLARATIONS,
};


const Uint8 ATT_TYPE_INCLUDE[] =
{
    GATT_DECLARATIONS_INCLUDE, GATT_DECLARATIONS,
};


const Uint8 ATT_TYPE_CHARACTERISTIC[] =
{
    GATT_DECLARATIONS_CHARACTERISTIC, GATT_DECLARATIONS,
};


const Uint8 ATT_TYPE_DESC_CHARC_EXTENDED_PROPERTIES[] =
{
    GATT_DESCRIPTORS_CHARACTERISTIC_EXTENDED_PROPERTIES, GATT_DESCRIPTORS,
};


const Uint8 ATT_TYPE_DESC_CHARC_USER_DESCRIPTION[] =
{
    GATT_DESCRIPTORS_CHARACTERISTIC_USER_DESCRIPTION, GATT_DESCRIPTORS,
};


const Uint8 ATT_TYPE_DESC_CLIENT_CHAR_CONFIGURATION[] =
{
    GATT_DESCRIPTORS_CLIENT_CHARACTERISTIC_CONFIGURATION, GATT_DESCRIPTORS,
};


const Uint8 ATT_TYPE_DESC_SERVER_CHAR_CONFIGURATION[] =
{
    GATT_DESCRIPTORS_SERVER_CHARACTERISTIC_CONFIGURATION, GATT_DESCRIPTORS,
};


const Uint8 ATT_TYPE_DESC_CHARC_PRESENTATION_FORMAT[] =
{
    GATT_DESCRIPTORS_CHARACTERISTIC_PRESENTATION_FORMAT, GATT_DESCRIPTORS,
};


const Uint8 ATT_TYPE_DESC_CHARC_AGGREGATE_FORMAT[] =
{
    GATT_DESCRIPTORS_CHARACTERISTIC_AGGREGATE_FORMAT, GATT_DESCRIPTORS,
};


const Uint8 ATT_TYPE_DESC_VALID_RANGE[] =
{
    GATT_DESCRIPTORS_VALID_RANGE, GATT_DESCRIPTORS,
};


const Uint8 ATT_TYPE_DESC_EXTERNAL_REPORT_REFERENCE[] =
{
    GATT_DESCRIPTORS_EXTERNAL_REPORT_REFERENCE, GATT_DESCRIPTORS,
};


const Uint8 ATT_TYPE_DESC_REPORT_REFERENCE[] =
{
    GATT_DESCRIPTORS_REPORT_REFERENCE, GATT_DESCRIPTORS,
};


const Uint8 ATT_VALUE_SERVICE_GAP[] =
{
    GATT_SPEC_SERVICES_GENERIC_ACCESS, GATT_SPEC_SERVICES,
};


const Uint8 ATT_VALUE_SERVICE_HRS[] =
{
    GATT_SPEC_SERVICES_HEART_RATE, GATT_SPEC_SERVICES,
};


const Uint8 ATT_VALUE_CHARC_HEART_RATE_MEASUREMENT[] =
{
    GATT_SPEC_CHARACTERISTIC_HEART_RATE_MEASUREMENT, GATT_SPEC_CHARACTERISTIC,
};


ATT_Handle ATT_INVALID_HDL_num =
{
    0,
    0,
    0,
};


const ATT_Value ATT_INVALID_HDL_value =
{
    sizeof(ATT_INVALID_TYPE),
    ATT_INVALID_TYPE,
};


const ATTRIBUTE_CLIENT ATT_INVALID =
{
    &ATT_INVALID_HDL_num,
    ATT_INVALID_TYPE,
    &ATT_INVALID_HDL_value,
    ATT_NULL_Noti_Indi,
};


ATT_Handle ATT_GAP_PRIMARY_SERVICE_HDL_num =
{
    0,
    ATT_TYPE_FORMAT_16UUID,
    GATT_DECLARATIONS_PROPERTIES_READ,
};


const ATT_Value ATT_GAP_PRIMARY_SERVICE_HDL_value =
{
    sizeof(ATT_VALUE_SERVICE_GAP),
    ATT_VALUE_SERVICE_GAP,
};


const ATTRIBUTE_CLIENT ATT_GAP_PRIMARY_SERVICE =
{
    &ATT_GAP_PRIMARY_SERVICE_HDL_num,
    ATT_TYPE_PRIMARY_SERVICE,
    &ATT_GAP_PRIMARY_SERVICE_HDL_value,
    ATT_NULL_Noti_Indi,
};


ATT_Handle ATT_GAP_CHARC_DEVICE_NAME_HDL_num =
{
    0,
    ATT_TYPE_FORMAT_16UUID,
    GATT_DECLARATIONS_PROPERTIES_READ,
};


const ATTRIBUTE_CLIENT ATT_GAP_CHARC_DEVICE_NAME =
{
    &ATT_GAP_CHARC_DEVICE_NAME_HDL_num,
    ATT_TYPE_CHARACTERISTIC,
    NULL,
    ATT_NULL_Noti_Indi,
};


#ifdef _PROFILE_CLI_HRP_
ATT_Handle ATT_HRS_PRIMARY_SERVICE_HDL_num =
{
    0,
    ATT_TYPE_FORMAT_16UUID,
    GATT_DECLARATIONS_PROPERTIES_READ,
};


const ATT_Value ATT_HRS_PRIMARY_SERVICE_HDL_value =
{
    sizeof(ATT_VALUE_SERVICE_HRS),
    ATT_VALUE_SERVICE_HRS,
};


const ATTRIBUTE_CLIENT ATT_HRS_PRIMARY_SERVICE =
{
    &ATT_HRS_PRIMARY_SERVICE_HDL_num,
    ATT_TYPE_PRIMARY_SERVICE,
    &ATT_HRS_PRIMARY_SERVICE_HDL_value,
    ATT_NULL_Noti_Indi,
};


ATT_Handle ATT_HRS_CHARC_HEART_RATE_MEASUREMENT_HDL_num =
{
    0,
    ATT_TYPE_FORMAT_16UUID,
    GATT_DECLARATIONS_PROPERTIES_READ,
};


const ATT_Value ATT_HRS_CHARC_HEART_RATE_MEASUREMENT_HDL_value =
{
    //5,
    //&ATT_HDL_HRS_CHARACTERISTIC_HEART_RATE_MEASUREMENT[5],
    sizeof(ATT_VALUE_CHARC_HEART_RATE_MEASUREMENT),
    ATT_VALUE_CHARC_HEART_RATE_MEASUREMENT,
};


const ATTRIBUTE_CLIENT ATT_HRS_CHARC_HEART_RATE_MEASUREMENT =
{
    &ATT_HRS_CHARC_HEART_RATE_MEASUREMENT_HDL_num,
    ATT_TYPE_CHARACTERISTIC,
    &ATT_HRS_CHARC_HEART_RATE_MEASUREMENT_HDL_value,
    ATT_NULL_Noti_Indi,
};


ATT_Handle ATT_HRS_HEART_RATE_MEASUREMENT_HDL_num =
{
    0,
    ATT_TYPE_FORMAT_16UUID,
    GATT_DECLARATIONS_PROPERTIES_NOTIFY,
};


const ATTRIBUTE_CLIENT ATT_HRS_HEART_RATE_MEASUREMENT =
{
    &ATT_HRS_HEART_RATE_MEASUREMENT_HDL_num,
    ATT_VALUE_CHARC_HEART_RATE_MEASUREMENT,
    NULL,
    ATT_HRS_Noti,
};




ATT_Handle ATT_HRS_CLIENT_CHARC_CONFIGURATION_HDL_num =
{
    0,
    ATT_TYPE_FORMAT_16UUID,
    {
        GATT_DECLARATIONS_PROPERTIES_READ |
        GATT_DECLARATIONS_PROPERTIES_WRITE |
        0x00
    },
};


Uint8 ATT_VALUE_HRS_CLIENT_CHARC_CONFIGURATION[] =
{
    {
        //GATT_DESCRIPTORS_CLIENT_CHARACTERISTIC_CONFIGURATION_NOTIFICATION |
        //GATT_DESCRIPTORS_CLIENT_CHARACTERISTIC_CONFIGURATION_INDICATION |
        0x00
    },                ///Attribute Value, little endian, UINT16
    0x00
};


const ATT_Value ATT_HRS_CLIENT_CHARC_CONFIGURATION_HDL_value =
{
    sizeof(ATT_VALUE_HRS_CLIENT_CHARC_CONFIGURATION),
    ATT_VALUE_HRS_CLIENT_CHARC_CONFIGURATION,
};


const ATTRIBUTE_CLIENT ATT_HRS_CLIENT_CHARC_CONFIGURATION =
{
    &ATT_HRS_CLIENT_CHARC_CONFIGURATION_HDL_num,
    ATT_TYPE_DESC_CLIENT_CHAR_CONFIGURATION,
    &ATT_HRS_CLIENT_CHARC_CONFIGURATION_HDL_value,
    ATT_NULL_Noti_Indi,
};

/*
const ATTRIBUTE_CLIENT ATT_HRS_CHARACTERISTIC_BODY_SENSOR_LOCATION = {
    NULL,
    ATT_TYPE_CHARACTERISTIC,
    NULL,
};


const ATTRIBUTE_CLIENT ATT_HRS_BODY_SENSOR_LOCATION_INIT = {
};
*/
#endif  //(#ifdef _PROFILE_CLI_HRP_)

#ifdef _PROFILE_CLI_CSTM_UDF01S_
ATT_Handle ATT_UDF01S_PRIMARY_SERVICE_HDL_num =
{
    0,
    ATT_TYPE_FORMAT_128UUID,
    GATT_DECLARATIONS_PROPERTIES_READ,
};


const Uint8 ATT_VALUE_SERVICE_UDF01S[] =
{
    0xFF, 0xEE, 0xDD, 0xCC,
    0xBB, 0xAA, 0x99, 0x88,
    0x77, 0x66, 0x55, 0x44,
    0x33, 0x22, 0x11, 0x00
};


const ATT_Value ATT_UDF01S_PRIMARY_SERVICE_HDL_value =
{
    sizeof(ATT_VALUE_SERVICE_UDF01S),
    ATT_VALUE_SERVICE_UDF01S,
};


const ATTRIBUTE_CLIENT ATT_UDF01S_PRIMARY_SERVICE =
{
    &ATT_UDF01S_PRIMARY_SERVICE_HDL_num,
    ATT_TYPE_PRIMARY_SERVICE,
    &ATT_UDF01S_PRIMARY_SERVICE_HDL_value,
    ATT_NULL_Noti_Indi,
};


ATT_Handle ATT_UDF01S_CHARC_UDATR01_HDL_num =
{
    0,
    ATT_TYPE_FORMAT_16UUID,
    GATT_DECLARATIONS_PROPERTIES_READ,
};


const Uint8 ATT_VALUE_CHARC_UDF01S_UDATR01[] =
{
    0x1F, 0x1E, 0x1D, 0x1C,
    0x1B, 0x1A, 0x19, 0x18,
    0x17, 0x16, 0x15, 0x14,
    0x13, 0x12, 0x11, 0x10
};


const ATT_Value ATT_UDF01S_CHARC_UDATR01_HDL_value =
{
    sizeof(ATT_VALUE_CHARC_UDF01S_UDATR01),
    ATT_VALUE_CHARC_UDF01S_UDATR01,
};


const ATTRIBUTE_CLIENT ATT_UDF01S_CHARC_UDATR01 =
{
    &ATT_UDF01S_CHARC_UDATR01_HDL_num,
    ATT_TYPE_CHARACTERISTIC,
    &ATT_UDF01S_CHARC_UDATR01_HDL_value,
    ATT_NULL_Noti_Indi,
};


ATT_Handle ATT_UDF01S_UDATR01_HDL_num =
{
    0,
    ATT_TYPE_FORMAT_16UUID,
    GATT_DECLARATIONS_PROPERTIES_NOTIFY,
};


const ATTRIBUTE_CLIENT ATT_UDF01S_UDATR01 =
{
    &ATT_UDF01S_UDATR01_HDL_num,
    ATT_VALUE_CHARC_UDF01S_UDATR01,
    NULL,
    ATT_NULL_Noti_Indi,
};


ATT_Handle ATT_UDF01S_CHARC_UDATN01_HDL_num =
{
    0,
    ATT_TYPE_FORMAT_16UUID,
    GATT_DECLARATIONS_PROPERTIES_READ,
};


const Uint8 ATT_VALUE_CHARC_UDF01S_UDATN01[] =
{
    GATT_SPEC_CSTM_CHARACTERISTIC_UDATN01, GATT_SPEC_CSTM_CHARACTERISTIC                                //Attribute Value
};


const ATT_Value ATT_UDF01S_CHARC_UDATN01_HDL_value =
{
    //5,
    //&ATT_HDL_HRS_CHARACTERISTIC_HEART_RATE_MEASUREMENT[5],
    sizeof(ATT_VALUE_CHARC_UDF01S_UDATN01),
    ATT_VALUE_CHARC_UDF01S_UDATN01,
};


const ATTRIBUTE_CLIENT ATT_UDF01S_CHARC_UDATN01 =
{
    &ATT_UDF01S_CHARC_UDATN01_HDL_num,
    ATT_TYPE_CHARACTERISTIC,
    &ATT_UDF01S_CHARC_UDATN01_HDL_value,
    ATT_NULL_Noti_Indi,
};


ATT_Handle ATT_UDF01S_UDATN01_HDL_num =
{
    0,
    ATT_TYPE_FORMAT_16UUID,
    GATT_DECLARATIONS_PROPERTIES_NOTIFY,
};


const ATTRIBUTE_CLIENT ATT_UDF01S_UDATN01 =
{
    &ATT_UDF01S_UDATN01_HDL_num,
    ATT_VALUE_CHARC_UDF01S_UDATN01,
    NULL,
    ATT_UDF01S_UDATN01_Noti,
};


ATT_Handle ATT_UDF01S_UDATN01_CLIENT_CHARC_CONFIGURATION_HDL_num =
{
    0,
    ATT_TYPE_FORMAT_16UUID,
    {
        GATT_DECLARATIONS_PROPERTIES_READ |
        GATT_DECLARATIONS_PROPERTIES_WRITE |
        0x00
    },
};


Uint8 ATT_VALUE_UDF01S_UDATN01_CLIENT_CHARC_CONFIGURATION[] =
{
    {
        //GATT_DESCRIPTORS_CLIENT_CHARACTERISTIC_CONFIGURATION_NOTIFICATION |
        //GATT_DESCRIPTORS_CLIENT_CHARACTERISTIC_CONFIGURATION_INDICATION |
        0x00
    },                         ///Attribute Value, little endian, UINT16
    0x00
};


const ATT_Value ATT_UDF01S_UDATN01_CLIENT_CHARC_CONFIGURATION_HDL_value =
{
    sizeof(ATT_VALUE_UDF01S_UDATN01_CLIENT_CHARC_CONFIGURATION),
    ATT_VALUE_UDF01S_UDATN01_CLIENT_CHARC_CONFIGURATION,
};


const ATTRIBUTE_CLIENT ATT_UDF01S_UDATN01_CLIENT_CHARC_CONFIGURATION =
{
    &ATT_UDF01S_UDATN01_CLIENT_CHARC_CONFIGURATION_HDL_num,
    ATT_TYPE_DESC_CLIENT_CHAR_CONFIGURATION,
    &ATT_UDF01S_UDATN01_CLIENT_CHARC_CONFIGURATION_HDL_value,
    ATT_NULL_Noti_Indi,
};


//ATT_UDF01S_CHARC_UDATRW01,
//ATT_UDF01S_UDATRW01,
ATT_Handle ATT_UDF01S_CHARC_UDATRW01_HDL_num =
{
    0,
    ATT_TYPE_FORMAT_16UUID,
    GATT_DECLARATIONS_PROPERTIES_READ,
};


const Uint8 ATT_VALUE_CHARC_UDF01S_UDATRW01[] =
{
    0x5F, 0x5E, 0x5D, 0x5C,
    0x5B, 0x5A, 0x59, 0x58,
    0x57, 0x56, 0x55, 0x54,
    0x53, 0x52, 0x51, 0x50
};


const ATT_Value ATT_UDF01S_CHARC_UDATRW01_HDL_value =
{
    sizeof(ATT_VALUE_CHARC_UDF01S_UDATRW01),
    ATT_VALUE_CHARC_UDF01S_UDATRW01,
};


const ATTRIBUTE_CLIENT ATT_UDF01S_CHARC_UDATRW01 =
{
    &ATT_UDF01S_CHARC_UDATRW01_HDL_num,
    ATT_TYPE_CHARACTERISTIC,
    &ATT_UDF01S_CHARC_UDATRW01_HDL_value,
    ATT_NULL_Noti_Indi,
};


ATT_Handle ATT_UDF01S_UDATRW01_HDL_num =
{
    0,
    ATT_TYPE_FORMAT_128UUID,
    GATT_DECLARATIONS_PROPERTIES_NOTIFY,
};


const ATTRIBUTE_CLIENT ATT_UDF01S_UDATRW01 =
{
    &ATT_UDF01S_UDATRW01_HDL_num,
    ATT_VALUE_CHARC_UDF01S_UDATRW01,
    NULL,
    ATT_NULL_Noti_Indi,
};

#endif  //(#ifdef _PROFILE_CLI_CSTM_UDF01S_)


const ATTRIBUTE_CLIENT *ATT_SERVER_CLIENT[] =
{
    //&ATT_INVALID,
    &ATT_GAP_PRIMARY_SERVICE,
    &ATT_GAP_CHARC_DEVICE_NAME,
#ifdef _PROFILE_CLI_HRP_
    &ATT_HRS_PRIMARY_SERVICE,
    &ATT_HRS_CHARC_HEART_RATE_MEASUREMENT,
    &ATT_HRS_HEART_RATE_MEASUREMENT,
    &ATT_HRS_CLIENT_CHARC_CONFIGURATION,
    //ATT_HRS_CHARACTERISTIC_BODY_SENSOR_LOCATION,
    //ATT_HRS_BODY_SENSOR_LOCATION_INIT,
#endif  //(#ifdef _PROFILE_CLI_HRP_)
#ifdef _PROFILE_CLI_CSTM_UDF01S_
    &ATT_UDF01S_PRIMARY_SERVICE,
    &ATT_UDF01S_CHARC_UDATR01,
    &ATT_UDF01S_UDATR01,
    &ATT_UDF01S_CHARC_UDATN01,
    &ATT_UDF01S_UDATN01,
    &ATT_UDF01S_UDATN01_CLIENT_CHARC_CONFIGURATION,
    &ATT_UDF01S_CHARC_UDATRW01,
    &ATT_UDF01S_UDATRW01,
#endif  //(#ifdef _PROFILE_CLI_CSTM_UDF01S_)
};


#define SIZE_ATT_SERVER_CLIENT (sizeof(ATT_SERVER_CLIENT)/sizeof(ATT_SERVER_CLIENT[0]))
Uint8 size_ATT_SERVER_CLIENT = SIZE_ATT_SERVER_CLIENT;


#pragma push
#pragma O1
#pragma Otime
void init_ATT_SERVER_CLIENT(void)
{
    extern Uint16 status_cli_HDL_Srv, status_cli_HDL_Charc;
    Uint8 i;
    //ATT_TYPE_SERVICE *p;

    for(i=0; i<SIZE_ATT_SERVER_CLIENT; i++)
    {
        //p = (ATT_TYPE_SERVICE *)&ATT_SERVER_CLIENT[i];
        //p->handleNum = &handle[i][0];
        ATT_SERVER_CLIENT[i]->handle->handle_Num = 0;
    }
    status_cli_HDL_Srv = HS_ATT_CLI_SRV_S0;
    status_cli_HDL_Charc = HS_ATT_CLI_CHR_S0;
};
#pragma pop


#endif  //(#ifdef _HOST_CLIENT_)
#endif

